# Generated by Django 5.0.1 on 2024-01-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iso", models.CharField(max_length=3)),
                ("long_name", models.CharField(max_length=50)),
            ],
        ),
    ]
